<!DOCTYPE html>


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="../css/studentList.css">
    <title>Document</title>
    <link rel="stylesheet" href="../css/header.css">
</head>
<header>
    <nav>
        <ul>
            <li><a href="studentList.php">Student list</a></li>
            <li><a href="reg.php">Reg or make changes</a></li>
        </ul>
    </nav>
</header>