<html lang="en">
<?php require_once "header.phtml" ?>

<body>

    <table class="content-table">
        <thead>
            <tr>
                <th class="name">Name</th>
                <th>Last name</th>
                <th>Gender</th>
                <th>Group</th>
                <th>Total points</th>
                <th>year of birth</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <!-- here need data -->






        </tbody>
    </table>

</body>

</html>