<html lang="en">
<?php require_once "header.phtml" ?>

<body>

    <table class="content-table">
        <thead>
            <tr>
                <th class="name">Name</th>
                <th>Last name</th>
                <th>Gender</th>
                <th>Group</th>
                <th>Total points</th>
                <th>year of birth</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <!-- here need data -->
            <?php foreach ($students as $student) : ?>
                <tr>
                    <td><?= $student->name ?></td>
                    <td><?= $student->lastname ?></td>
                    <td><?= $student->gender ?></td>
                    <td><?= $student->group_ ?></td>
                    <td><?= $student->useResult ?></td>
                    <td><?= $student->birthYear ?></td>
                    <td><?= $student->email ?></td>
                </tr>
            <?php endforeach; ?>





        </tbody>
    </table>

</body>

</html>